### PR TITLE
Added team members of DMN and SCESIM editors

### PR DESCRIPTION
**Pull request by yesamer**
@LightGuard @karreiro @vpellegrino @danielzhe

### CODE REVIEW

**Review by karreiro — COMMENTED** [review]
Thank you, @yesamer!

I've noticed that @vpellegrino and @danielzhe images are not loading:
image

May we use, respectively, these `img` URLs https://avatars.githubusercontent.com/u/22591802?v=4 https://avatars.githubusercontent.com/u/7305741?v=4 ?

**Comment by yesamer** [comment]
@karreiro FIne for me, let's wait for @vpellegrino and @danielzhe opinions

**Comment by vpellegrino** [comment]
> @karreiro FIne for me, let's wait for @vpellegrino and @danielzhe opinions

Sure, fine for me

**Comment by yesamer** [comment]
@karreiro @vpellegrino @danielzhe Updated.

**Review by karreiro — APPROVED** [review]
Thanks, @yesamer! It looks great now :-)

image

**Comment by yesamer** [comment]
`che belli uaglioni!` :D :D :D

**Review by vpellegrino — APPROVED** [review]
Thanks @yesamer

**Pull request merged**
